<?php
$name_ext = '';
if($this->data['product_return_id']){
    $name_ext = '(Hàng có sẵn)';
}
$xhtml = '
    <tr id="tr_'.$this->product['productId'].'" data-id="'.$this->product['productId'].'">
        <td width="100px" class="text-bold text-red text-middle">'.$this->product['code'].'</td>
        <td width="100px" class="text-middle">
            '.$this->product['fullName'].$name_ext.' 
            <a href="javascript:;" title="Xem chi tiết" class="btn btn-xs blue" onclick="javascript:popupInfor(\'/xadmin/contract/quick-product/\', {\'id\': \''.$this->product['productId'].'\'});"><i class="fa fa-info"></i></a>
        </td>
        <td class="product_name"><input class="form-control" type="text" name="contract_product[product_name][]" value=""></td>
        <td class="numbers"><input class="form-control text-right money" type="text" name="contract_product[numbers][]" value="1" min="1"></td>
        <td class="price text-middle text-right box-price">
            <span class="show-price">'.number_format($this->product['basePrice']).'</span>
            <span class="show_discount"></span>
            <input class="money base_price hidden" name="contract_product[price][]" type="text" value="'.number_format($this->product['basePrice']).'" min="0">
            <div class="price-detail">
                <p class="close-price-detail text-right text-red"><i class="fa fa-times"></i> </p>
                <p><span class="desc">Đơn giá </span><input class="listed_price" type="text" readonly value="'.number_format($this->product['basePrice']).'" min="0"></p>
                <p class="type-discount"><span class="desc">Giảm giá </span>
                    <input class="money discount_value" type="text" name="contract_product[discount_value][]" value="0" min="0">
                    <label><input class="unit_type" type="radio" name="contract_product[unit_type]['.$this->product['productId'].']" value="2" checked="checked">%</label>
                    <label><input class="unit_type" type="radio" name="contract_product[unit_type]['.$this->product['productId'].']" value="1">vnđ</label>
                </p>
                <p><span class="desc">Giá bán </span><input class="sale_text money" type="text" value="'.number_format($this->product['basePrice']).'" min="0"></p>
            </div>
        </td>
        <td class="listed_price text-right text-middle hidden">'.number_format($this->product['basePrice']).'</td>
        <td class="total"><input class="form-control text-right" type="text" name="contract_product[total][]" readonly value="'.number_format($this->product['basePrice']).'"></td>
        <td class="hidden">
            <input class="form-control" type="text" name="contract_product[is_gif][]" value="0">
            <input class="form-control" type="text" name="contract_product[product_return_id][]" value="'.$this->data['product_return_id'].'">
            <input class="form-control" type="text" name="contract_product[product_id][]" value="'.$this->product['productId'].'">
            <input class="form-control" type="text" name="contract_product[full_name][]" value="'.$this->product['fullName'].$name_ext.'">
            <input class="form-control" type="text" name="contract_product[code][]" value="'.$this->product['code'].'">
            <input class="form-control" type="text" name="contract_product[branch_id][]" value="'.$this->product['branchId'].'"> 
            <input class="form-control hidden" type="text" name="contract_product[listed_price][]" value="'.$this->product['basePrice'].'">
            <input class="form-control" type="text" name="contract_product[cost][]" value="'.$this->product['cost'].'"> 
            <input class="form-control" type="text" name="contract_product[cost_new][]" value="'.$this->product['cost_new'].'"> 
            <input class="form-control" type="text" name="contract_product[fee][]" value="'.$this->product['fee'].'"> 
            <input class="form-control" type="text" name="contract_product[capital_default][]" value="'.(int)($this->product['cost'] + ($this->product['cost'] * $this->product['cost_new'] / 100)).'"> 
        </td>
       
        <td><i class="fa fa-trash delete-row" aria-hidden="true" style="color:red; margin: 5px 0 0 5px; font-size: 20px;"></i></td>
    </tr>';
    echo $xhtml;
?>


