<link href="/public/template/backend/css/contract.css?v=<?php echo date('dmYHis');?>" media="screen" rel="stylesheet" type="text/css">
<?php
$myForm = $this->myForm;
$myForm->prepare();

$arrControl = array(
    array('name' => 'save', 'caption' => 'Lưu', 'link' => 'javascript:;', 'icon' => 'fa-check', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save\');', 'class' => 'btn')),
    array('name' => 'save-new', 'caption' => 'Lưu &amp; Mới', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-new\');', 'class' => 'btn')),
    array('name' => 'save-close', 'caption' => 'Lưu &amp; Đóng', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-close\');', 'class' => 'btn')),
    array('name' => 'close', 'caption' => 'Hủy', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
);

// Set lại các giá trị của từng element
$options = unserialize($this->contract['options']);
$myForm->get('name_received')->setValue($options['contract_received']['name']);
$myForm->get('phone_received')->setValue($options['contract_received']['phone']);
$myForm->get('address_received')->setValue($options['contract_received']['address']);

$elementsTop = array(
    array('section' => 'Thông tin đơn hàng + người nhận', 'boxClass' => 'col-md-12'),
    array('element' => $myForm->get('name_received'), 'label' => 'Tên người nhận', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
    array('element' => $myForm->get('phone_received'), 'label' => 'Số điện thoại', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
    array('element' => $myForm->get('address_received'), 'label' => 'Địa chỉ nhận hàng', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
    array('element' => $myForm->get('date'), 'label' => 'Ngày ký', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
    array('element' => $myForm->get('production_type_id'), 'label' => 'Loại đơn sản xuất', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
    array('element' => $myForm->get('sale_note'), 'label' => 'Ghi chú sales', 'boxClass' => 'col-md-2'),
);

$xhtmlTop = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elementsTop);

$elementsBottom = array(
    array('div' => '', 'boxClass' => 'col-md-12'),
    array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
);
$xhtmlBottom = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elementsBottom);
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" class="">
    <div class="page-control">
        <div class="title pull-left">
            <?php echo $this->caption;?>
        </div>
        <div class="control pull-right">
            <?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
        </div>
        <div class="clearfix"></div>
    </div>

    <?php echo $this->flashMessenger()->render();?>
    <?php echo @$this->xViewElementErrors($elementsTop);?>
    <?php echo @$this->xViewElementErrors($elementsBottom);?>

    <div class="page-content">
        <div class="row">
            <?php echo $xhtmlTop;?>
            <div class="col-md-12">
                <p class="text-alert"></p>
                <?php
                if(!empty($this->check_product_id)){
                    ?>
                    <div class="alert alert-block alert-danger">
                        <button type="button" class="close" data-dismiss="alert"></button>
                        <p><?php echo $this->check_product_id; ?></p>
                    </div>
                    <?php
                }
                ?>
            </div>
        </div>
        <div class="col-md-9">
            <h3 class="form-section">Danh sách sản phẩm</h3>
            <div class="contract_product table-scrollable" style="min-height: 300px" >
                <table class="table table-striped table-bordered table-hover table-product">
                    <thead>
                    <tr>
                        <th width="100px" class="text-center">Mã sản phẩm</th>
                        <th width="150px" class="text-center">Tên sản phẩm</th>
                        <th width="150px" class="text-center">Tên xe - năm sản xuất</th>
                        <th width="80px" class="text-center">Số lượng</th>
                        <th width="100px" class="text-center">Giá tiền</th>
<!--                        <th width="100px" class="text-center">Giá niêm yết</th>-->
                        <th width="100px" class="text-center">Thành tiền</th>
                        <th width="30px" class="text-center">Xóa</th>
                    </tr>
                    </thead>
                    <tbody class="product_body list-product-contract">
                    <?php
                    if(!empty($this->productList)){
                        $number   = new \ZendX\Functions\Number();
                        $productList = $this->productList;
                        $productHtml = '';
                        for($i = 0; $i < count($productList['product_id']); $i++) {
                            $check_name = empty($productList['product_name'][$i]) ? 'has-error' : "";
                            $check_number = empty($productList['numbers'][$i]) ? 'has-error' : "";
                            $check_price = empty($productList['price'][$i]) ? 'has-error' : "";
                            $tr_name = $productList['is_gif'][$i] == 1 ?  'class="product_gif"' : 'id="tr_'.$productList['product_id'][$i].'"';
                            if($productList['is_gif'][$i] == 1)
                                $text_number = '<td class="numbers text-right text-middle" style="padding:0px 17px;" > 1 <input class="hidden" type="text" name="contract_product[numbers][]" value="1" min="1"></td>';
                            else
                                $text_number = '<td class="numbers '.$check_number.'"><input class="form-control text-right money" type="text" name="contract_product[numbers][]" value="'.$productList['numbers'][$i].'" min="1"></td>';

                            $check1 = $productList['unit_type'][$i] == 1 ? 'checked' : '';
                            $check2 = $productList['unit_type'][$i] == 2 ? 'checked' : '';
                            $unit = $productList['unit_type'][$i] == 1 ? '' : ' %';
                            if(!empty($productList['discount_value'][$i])){
                                $show_discount = '- '.$productList['discount_value'][$i].$unit;
                            }
                            else {
                                if($number->formatToData($productList['price'][$i]) - $productList['listed_price'][$i] > 0) {
                                    $show_discount = '+ ' . number_format($number->formatToData($productList['price'][$i]) - $productList['listed_price'][$i]);
                                }
                            }

                            $productHtml .= '<tr '.$tr_name.' data-id="'.$productList['product_id'][$i].'">
                                                        <td width="100px" class="text-bold text-red text-middle">'.$productList['code'][$i].'</td>
                                                        <td width="100px" class="text-middle">'.$productList['full_name'][$i].'</td>
                                                        <td class="product_name '.$check_name.'"><input class="form-control" type="text" name="contract_product[product_name][]" value="'.$productList['product_name'][$i].'" ></td>
                                                        '.$text_number.'
                                                        
                                                        <td class="price text-middle text-right box-price">
                                                            <span class="show-price">'.number_format($productList['listed_price'][$i]).'</span>
                                                            <span class="show_discount">'.$show_discount.'</span>
                                                            <input class="money base_price hidden" name="contract_product[price][]" type="text" value="'.$productList['price'][$i].'" min="0">
                                                            <div class="price-detail">
                                                                <p class="close-price-detail text-right text-red"><i class="fa fa-times"></i> </p>
                                                                <p><span class="desc">Đơn giá </span><input class="listed_price" type="text" readonly value="'.number_format($productList['listed_price'][$i]).'" min="0"></p>
                                                                <p class="type-discount"><span class="desc">Giảm giá </span>
                                                                    <input class="money discount_value" type="text" name="contract_product[discount_value][]" value="'.$productList['discount_value'][$i].'" min="0">
                                                                    <label><input class="unit_type" type="radio" name="contract_product[unit_type]['.$productList['product_id'][$i].']" value="2" '.$check2.'>%</label>
                                                                    <label><input class="unit_type" type="radio" name="contract_product[unit_type]['.$productList['product_id'][$i].']" value="1" '.$check1.'>vnđ</label>
                                                                </p>
                                                                <p><span class="desc">Giá bán </span><input class="sale_text money" type="text" value="'.$productList['price'][$i].'" min="0"></p>
                                                            </div>
                                                        </td>
                                                        
                                                        
                                                        <td class="text-middle text-right hidden">'.number_format($productList['listed_price'][$i]).'</td>
                                                        <td class="total"><input class="form-control text-right" type="text" name="contract_product[total][]" value="'.$productList['total'][$i].'" readonly></td>
                                                        <td class="hidden">
                                                            <input class="form-control" type="text" name="contract_product[is_gif][]" value="'.$productList['is_gif'][$i].'">
                                                            <input class="form-control" type="text" name="contract_product[product_return_id][]" value="'.$productList['product_return_id'][$i].'">
                                                            <input class="form-control" type="text" name="contract_product[product_id][]" value="'.$productList['product_id'][$i].'">
                                                            <input class="form-control" type="text" name="contract_product[full_name][]" value="'.$productList['full_name'][$i].'">
                                                            <input class="form-control" type="text" name="contract_product[code][]" value="'.$productList['code'][$i].'">
                                                            <input class="form-control" type="text" name="contract_product[branch_id][]" value="'.$productList['branch_id'][$i].'">
                                                            <input class="form-control" type="text" name="contract_product[listed_price][]" value="'.$productList['listed_price'][$i].'"> 
                                                            <input class="form-control" type="text" name="contract_product[cost][]" value="'.$productList['cost'][$i].'"> 
                                                            <input class="form-control" type="text" name="contract_product[cost_new][]" value="'.$productList['cost_new'][$i].'"> 
                                                            <input class="form-control" type="text" name="contract_product[fee][]" value="'.$productList['fee'][$i].'"> 
                                                            <input class="form-control" type="text" name="contract_product[capital_default][]" value="'.(int)($productList['cost'][$i] + ($productList['cost'][$i] * $productList['cost_new'][$i] / 100)).'"> 
                                                        </td>
                                                       
                                                        <td><i class="fa fa-trash delete-row" aria-hidden="true" style="color:red; margin: 5px 0 0 5px; font-size: 20px;"></i></td>
                                                    </tr>';
                        }
                        echo $productHtml;
                    }
                    else if(!empty($this->option_product)){
                        $productHtml = '';
                        foreach($this->option_product as $pro_item){
                            $check1 = $pro_item['unit_type'] == 1 ? 'checked' : '';
                            $check2 = $pro_item['unit_type'] == 2 ? 'checked' : '';
                            $unit = $pro_item['unit_type'] == 1 ? '' : ' %';
                            $show_discount = '';
                            if($pro_item['discount_value']){
                                $show_discount = '- '.number_format($pro_item['discount_value']).$unit;
                            }
                            else if($pro_item['price'] - ($pro_item['listed_price'] / $pro_item['numbers']) > 0){
                                $show_discount = '+ '.number_format($pro_item['price'] - ($pro_item['listed_price'] / $pro_item['numbers']));
                            }


                            $tr_name = $pro_item['is_gif'] == 1 ? 'class="product_gif"' : 'id="tr_'.$pro_item['product_id'].'"';
                            if($pro_item['is_gif'] == 1)
                                $text_number = '<td class="numbers text-right text-middle" style="padding:0px 17px;" > 1 <input class="hidden" type="text" name="contract_product[numbers][]" value="1" min="1"></td>';
                            else
                                $text_number = '<td class="numbers "><input class="form-control text-right money" type="text" name="contract_product[numbers][]" value="'.$pro_item['numbers'].'" min="1"></td>';
                                $productHtml .= '<tr '.$tr_name.' data-id="'.$pro_item['product_id'].'">
                                                        <td width="100px" class="text-bold text-red text-middle">'.$pro_item['code'].'</td>
                                                        <td width="100px" class="text-middle">'.$pro_item['full_name'].'</td>
                                                        <td class="product_name "><input class="form-control" type="text" name="contract_product[product_name][]" value="'.$pro_item['product_name'].'" ></td>
                                                        '.$text_number.'
                                                        
                                                        <td class="price text-middle text-right box-price">
                                                            <span class="show-price">'.number_format($pro_item['listed_price']  / $pro_item['numbers']).'</span>
                                                            <span class="show_discount">'.$show_discount.'</span>
                                                            <input class="money base_price hidden" name="contract_product[price][]" type="text" value="'.number_format($pro_item['price']).'" min="0">
                                                            <div class="price-detail">
                                                                <p class="close-price-detail text-right text-red"><i class="fa fa-times"></i> </p>
                                                                <p><span class="desc">Đơn giá </span><input class="listed_price" type="text" readonly value="'.number_format($pro_item['listed_price']  / $pro_item['numbers']).'" min="0"></p>
                                                                <p class="type-discount"><span class="desc">Giảm giá </span>
                                                                    <input class="money discount_value" type="text" name="contract_product[discount_value][]" value="'.number_format($pro_item['discount_value']).'" min="0">
                                                                    <label><input class="unit_type" type="radio" name="contract_product[unit_type]['.$pro_item['product_id'].']" value="2" '.$check2.'>%</label>
                                                                    <label><input class="unit_type" type="radio" name="contract_product[unit_type]['.$pro_item['product_id'].']" value="1" '.$check1.'>vnđ</label>
                                                                </p>
                                                                <p><span class="desc">Giá bán </span><input class="sale_text money" type="text" value="'.number_format($pro_item['price']).'" min="0"></p>
                                                            </div>
                                                        </td>
                                                        
                                                        
                                                        <td class="text-middle text-right hidden">'.number_format($pro_item['listed_price']  / $pro_item['numbers']).'</td>
                                                        <td class="total"><input class="form-control text-right" type="text" name="contract_product[total][]" value="'.number_format($pro_item['total']).'" readonly></td>
                                                        <td class="hidden">
                                                            <input class="form-control" type="text" name="contract_product[is_gif][]" value="'.$pro_item['is_gif'].'">
                                                            <input class="form-control" type="text" name="contract_product[product_return_id][]" value="'.$pro_item['product_return_id'].'">
                                                            <input class="form-control" type="text" name="contract_product[product_id][]" value="'.$pro_item['product_id'].'">
                                                            <input class="form-control" type="text" name="contract_product[full_name][]" value="'.$pro_item['full_name'].'">
                                                            <input class="form-control" type="text" name="contract_product[code][]" value="'.$pro_item['code'].'">
                                                            <input class="form-control" type="text" name="contract_product[branch_id][]" value="'.$pro_item['branch_id'].'">
                                                            <input class="form-control" type="text" name="contract_product[listed_price][]" value="'.($pro_item['listed_price'] / $pro_item['numbers']).'"> 
                                                            <input class="form-control" type="text" name="contract_product[cost][]" value="'.$pro_item['cost'].'"> 
                                                            <input class="form-control" type="text" name="contract_product[cost_new][]" value="'.$pro_item['cost_new'].'"> 
                                                            <input class="form-control" type="text" name="contract_product[fee][]" value="'.$pro_item['fee'].'"> 
                                                            <input class="form-control" type="text" name="contract_product[capital_default][]" value="'.(int)($pro_item['cost'] + ($pro_item['cost'] * $pro_item['cost_new'] / 100)) .'"> 
                                                        </td>
                                                       
                                                        <td><i class="fa fa-trash delete-row" aria-hidden="true" style="color:red; margin: 5px 0 0 5px; font-size: 20px;"></i></td>
                                                    </tr>';
                        }
                        echo $productHtml;
                    }
                    ?>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-3">
            <h3 class="form-section">Thành tiền hóa đơn</h3>
            <div class="contract_product" style="width: 100%;">
                <table class="table table-striped table-bordered table-hover table-product">
                    <thead>
                    <tr><th>Mô tả</th><th>Giá trị</th></tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <td class="text-middle">Tổng tiền hàng</td>
<!--                        <td class="total_contract_product"><input class="form-control text-right money" type="text" name="total_contract_product"  value="0"></td>-->
                        <td class="total_contract_product text-right text-middle" style="padding: 0px 17px;"><span></span><input class="form-control hidden" type="text" name="total_contract_product"  value="0"></td>
                    </tr>
                    <tr>
                        <td class="text-middle">Tổng tiền thuế VAT</td>
                        <td class="total_contract_vat"><input class="form-control text-right money" type="text" name="total_contract_vat" value="<?php if($this->contract['vat']) echo number_format($this->contract['vat']);  else 0 ?>"></td>
                    </tr>
                    <tr>
                        <td class="text-middle">Thu khác</td>
                        <td class="fee_other"><input class="form-control text-right money" type="text" name="fee_other" value="<?php if($this->contract['fee_other']) echo number_format($this->contract['fee_other']);  else 0 ?>" min="0"></td>
                    </tr>
                    <tr>
                        <td class="text-middle">Giảm giá
                            <div id="gift"></div>
                        </td>
                        <td class="total_contract_discount"><input class="form-control text-right money" type="text" name="total_contract_discount" value="<?php if($this->contract['total_contract_discount']) echo number_format($this->contract['total_contract_discount']);  else 0 ?>" ></td>
                    </tr>
                    <tr>
                        <td class="text-middle">Khách cần trả</td>
<!--                        <td class="total_contract"><input class="form-control text-right" type="text" name="total_contract" value="0"></td>-->
                        <td class="total_contract text-right text-middle" style="padding: 0px 17px;"><span></span><input class="form-control hidden" type="text" name="total_contract" value="0"></td>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>

        <div class="col-md-12 form-section" style="padding: 0px;">
            <div>
                <span class="title-load-product">Sản phẩm</span>
            </div>
            <div class="col-md-3">
                <div class="form-group" style="margin-bottom: 5px;">
                    <select name="kov_product_category" class="form-control select2 select2_basic" style="display: none;">
                        <option value="">- Chọn nhóm hàng -</option>
                        <?php foreach($this->categories as $key => $value){?>
                            <option value="<?=$key?>"><?=$value?></option>
                            <?php
                        } ?>

                    </select>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <div class="control-element">
                        <input type="text" name="filter_keyword" class="form-control" value="" placeholder="Nhập tên sản phẩm" autocomplete="off">
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-12" style="padding: 0px;">
            <div id="loadProducts">
            </div>
        </div>
        <div class="col-md-12 form-section" style="padding: 0px;">
            <div>
                <span class="title-load-product">Hàng có sẵn</span>
            </div>
            <div class="col-md-3">
                <div class="form-group" style="margin-bottom: 5px;">
                    <select name="kov_product_return_category" class="form-control select2 select2_basic" style="display: none;">
                        <option value="">- Chọn nhóm hàng -</option>
                        <?php foreach($this->categories as $key => $value){?>
                            <option value="<?=$key?>"><?=$value?></option>
                            <?php
                        } ?>

                    </select>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <div class="control-element">
                        <input type="text" name="filter_keyword_return" class="form-control" value="" placeholder="Nhập tên sản phẩm" autocomplete="off">
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-12" style="padding: 0px;">
            <div id="loadProductsReturn">
            </div>
        </div>

        <div class="row">
            <?php echo $xhtmlBottom;?>
        </div>
    </div>
</form>
<div class="hidden" id="contactPhone">
    <?php echo $this->contactPhone;?>
</div>
<div class="hidden" id="contactId">
    <?php echo $this->contactId;?>
</div>

<link href="/public/template/backend/css/contract.css?v=<?php echo date('dmYHis');?>" media="screen" rel="stylesheet" type="text/css">
<?php $this->headScript()->captureStart() ?>
var params = JSON.parse('<?php echo json_encode($this->discounts_params); ?>');
<?php $this->headScript()->captureEnd() ?>
<?php $this->HeadScript()->appendFile('/public/template/backend/js/contracts/contract.js','text/javascript');?>




